repos:  
- repo: https://github.com/python-poetry/poetry  
  rev: '1.8.0'  # specify the version you want to use  
  hooks:  
  - id: poetry-check  
  - id: poetry-lock  
  - id: poetry-export  
  - id: poetry-install
  - id: poetry-export  
    args: ["-f", "requirements.txt", "-o", "requirements.txt"]  